# Generated by Django 4.1.7 on 2023-03-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalmartStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store', models.CharField(max_length=2, verbose_name='Store no')),
                ('Date', models.CharField(max_length=10, verbose_name='Date')),
                ('Weekly_Sales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Weekly Sales')),
                ('Holiday_Flag', models.CharField(choices=[('0', 'Workingday'), ('1', 'Holiday')], max_length=1, verbose_name='Holiday')),
                ('Temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature')),
                ('Fuel_Price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperature')),
                ('CPI', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='CPI')),
                ('Unemployment', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Unemployment')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
