# Generated by Django 4.1.7 on 2023-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walmartstore',
            name='Fuel_Price',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Temperature'),
        ),
    ]
