# Generated by Django 4.1.7 on 2023-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0003_product_rename_cpi_walmartstore_cpi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walmartsales',
            name='date',
        ),
        migrations.AddField(
            model_name='walmartsales',
            name='date_time',
            field=models.DateTimeField(null=True, verbose_name='Date time'),
        ),
    ]
