# Generated by Django 4.1.7 on 2023-04-20 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0004_remove_walmartsales_date_walmartsales_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='walmartsales',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='walmartsales',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date time'),
        ),
    ]
