# Generated by Django 4.1.7 on 2023-04-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0005_walmartsales_quantity_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walmartstore',
            name='cpi',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='CPI'),
        ),
        migrations.AlterField(
            model_name='walmartstore',
            name='fuel_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='walmartstore',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='walmartstore',
            name='unemployment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Unemployment'),
        ),
    ]
