# Generated by Django 4.1.7 on 2023-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0006_alter_walmartstore_cpi_alter_walmartstore_fuel_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walmartsales',
            name='store',
            field=models.CharField(max_length=2, verbose_name='Store no'),
        ),
    ]
