# Generated by Django 4.1.7 on 2023-04-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0007_alter_walmartsales_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walmartsales',
            old_name='store',
            new_name='store_no',
        ),
    ]
