# Generated by Django 4.1.7 on 2023-04-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0012_alter_walmartsales_isholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walmartsales',
            name='isHoliday',
        ),
    ]
