# Generated by Django 4.1.7 on 2024-02-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_analysis', '0014_productstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='store',
            field=models.PositiveSmallIntegerField(verbose_name='Store No.'),
        ),
    ]
